{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "labaclaw-worker-plane.serviceAccountName" . }}
  namespace: {{ .Values.workerPlane.namespace }}
{{- if .Values.serviceAccount.imagePullSecrets }}
imagePullSecrets:
{{- range .Values.serviceAccount.imagePullSecrets }}
  - name: {{ . }}
{{- end }}
{{- end }}
{{- end }}
